### ISSUE TITLE
Error: Service error:InvalidParameter. Invalid availabilityDomain. http status code: 400.

### ISSUE THREAD

**Issue by linhniit** [oracle-quickstart/oci-redis#9]
When i run terraform plan : var.availablity_domain_name ; Enter a value: 1
terraform apply ; var.availablity_domain_name ; Enter a value: 1

Then i got one error message : 

Error: Service error:InvalidParameter. Invalid availabilityDomain. http status code: 400. Opc request id: 46b9dcb2518905f7258b3ac5718c42db/45933F491EDCB2EF82F42E61A1498264/7005350FEF388FE05EB9A965BF358138

  on redis_masters.tf line 2, in resource "oci_core_instance" "redis1":
   2: resource "oci_core_instance" "redis1" {

**Comment by linhniit** [comment]
I use domain name that matching in Jeddah Region with value as below , You should find in When you create new Instance and use the whole value
ApKJ:ME-JEDDAH-1-AD-1

**Comment by linhniit** [comment]
Then i found another issue in global var 
in **redis_master.tf** $ **redis_replicas.tf** in var : in correct syntaxt 
```
Incorrect : data.oci_core_images.InstanceImageOCID.images[0].id
Corect : **_data.oci_core_images.InstanceImageOCID.images.0.id_**

It take me 5mins to get all of resources without any issue .
```

**Comment by lfeldman** [comment]
@linhniit thanks for the feedback. I have updated README to be clear you need to define availablity_domain_name in terraform.tfvars.
